### ISSUE TITLE
Crash report: `Error: [DecimalError] Invalid argument: undefined`

### ISSUE THREAD

**Issue by Dronurgultekin** [AnimeSwap/interface#18]
## URL
  
https://staging.animeswap.org/#/add/0x2a2ad97dfdbe4e34cdc9321c63592dda455f18bc25c9bb1f28260312159eae27::staked_aptos_coin::StakedAptosCoin/0x4dd8a22e95f3ec2448ee1cc6634298024095ce8baa3031650b3852af6e2d41d0::celer_coin_manager::WethCoin?chain=aptos_testnet

## `mint` state
    
```json
{
  "independentField": "COIN_A",
  "typedValue": "",
  "otherTypedValue": "0.05",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
Error: [DecimalError] Invalid argument: undefined
```

## Stacktrace

```
Error: [DecimalError] Invalid argument: undefined
    at new o (https://staging.animeswap.org/static/js/main.45ddf040.js:2:245744)
    at j.dividedBy.j.div (https://staging.animeswap.org/static/js/main.45ddf040.js:2:220933)
    at PN (https://staging.animeswap.org/static/js/main.45ddf040.js:2:1365296)
    at Sa (https://staging.animeswap.org/static/js/main.45ddf040.js:2:562928)
    at ku (https://staging.animeswap.org/static/js/main.45ddf040.js:2:620168)
    at bc (https://staging.animeswap.org/static/js/main.45ddf040.js:2:609104)
    at yc (https://staging.animeswap.org/static/js/main.45ddf040.js:2:609032)
    at gc (https://staging.animeswap.org/static/js/main.45ddf040.js:2:608895)
    at oc (https://staging.animeswap.org/static/js/main.45ddf040.js:2:605675)
    at uc (https://staging.animeswap.org/static/js/main.45ddf040.js:2:606066)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "106.0.0.0",
    "major": "106"
  },
  "engine": {
    "name": "Blink",
    "version": "106.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by Azard** [comment]
https://github.com/AnimeSwap/interface/commit/179aa8ca46636ffbfb3bade7863685ea4ef26215
