### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'address')`

### ISSUE THREAD

**Issue by gamadowload** [AnimeSwap/interface#31]
## URL
  
https://staging.animeswap.org/#/pool

## Error

```
TypeError: Cannot read properties of undefined (reading 'address')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'address')
    at $b (https://staging.animeswap.org/static/js/main.c7ed7558.js:2:1665182)
    at FK (https://staging.animeswap.org/static/js/main.c7ed7558.js:2:2169767)
    at _a (https://staging.animeswap.org/static/js/main.c7ed7558.js:2:997868)
    at Su (https://staging.animeswap.org/static/js/main.c7ed7558.js:2:1055108)
    at bc (https://staging.animeswap.org/static/js/main.c7ed7558.js:2:1044044)
    at gc (https://staging.animeswap.org/static/js/main.c7ed7558.js:2:1043972)
    at yc (https://staging.animeswap.org/static/js/main.c7ed7558.js:2:1043835)
    at oc (https://staging.animeswap.org/static/js/main.c7ed7558.js:2:1040615)
    at uc (https://staging.animeswap.org/static/js/main.c7ed7558.js:2:1041006)
    at Fi (https://staging.animeswap.org/static/js/main.c7ed7558.js:2:981589)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "110.0.0.0",
    "major": "110"
  },
  "engine": {
    "name": "Blink",
    "version": "110.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by Azard** [comment]
https://github.com/AnimeSwap/interface/commit/84e09e6a229165deeebe33dd1bb5e3bb09f121a3
