### ISSUE TITLE
Crash report: `Error: Invalid 'address' parameter 'f66b8224e15643e71f9fb9e6f72ab2ee59028880'.`

### ISSUE THREAD

**Issue by yakimets** [AnimeSwap/interface#32]
## URL
  
https://staging.animeswap.org/#/swap?chain=sui_devnet

## `swap` state
    
```json
{
  "INPUT": {
    "coinId": "0x1::aptos_coin::AptosCoin"
  },
  "OUTPUT": {
    "coinId": "0x16fe2df00ea7dde4a63409201f7f4e536bde7bb7335526a35d05111e68aa322c::AnimeCoin::ANI"
  },
  "typedValue": "",
  "independentField": "INPUT"
}
```

## Error

```
Error: Invalid 'address' parameter 'f66b8224e15643e71f9fb9e6f72ab2ee59028880'.
```

## Stacktrace

```
Error: Invalid 'address' parameter 'f66b8224e15643e71f9fb9e6f72ab2ee59028880'.
    at Ix (https://staging.animeswap.org/static/js/main.3e51f728.js:2:1700431)
    at QF (https://staging.animeswap.org/static/js/main.3e51f728.js:2:2046695)
    at _a (https://staging.animeswap.org/static/js/main.3e51f728.js:2:998279)
    at Su (https://staging.animeswap.org/static/js/main.3e51f728.js:2:1055519)
    at bc (https://staging.animeswap.org/static/js/main.3e51f728.js:2:1044455)
    at gc (https://staging.animeswap.org/static/js/main.3e51f728.js:2:1044383)
    at yc (https://staging.animeswap.org/static/js/main.3e51f728.js:2:1044246)
    at oc (https://staging.animeswap.org/static/js/main.3e51f728.js:2:1041026)
    at ic (https://staging.animeswap.org/static/js/main.3e51f728.js:2:1039577)
    at k (https://staging.animeswap.org/static/js/main.3e51f728.js:2:1108169)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "111.0.0.0",
    "major": "111"
  },
  "engine": {
    "name": "Blink",
    "version": "111.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by yakimets** [comment]
what to do?

**Comment by Azard** [comment]
it should have been fixed after next update tomorrow @yakimets

**Comment by yakimets** [comment]
nice
