### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading '0x1::aptos_coin::AptosCoin')`

### ISSUE THREAD

**Issue by lobore2131** [AnimeSwap/interface#33]
## URL
  
https://app.animeswap.org/

## Error

```
TypeError: Cannot read properties of undefined (reading '0x1::aptos_coin::AptosCoin')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading '0x1::aptos_coin::AptosCoin')
    at https://app.animeswap.org/static/js/main.e348792d.js:2:1683062
    at e (https://app.animeswap.org/static/js/main.e348792d.js:2:1199451)
    at https://app.animeswap.org/static/js/main.e348792d.js:2:1199656
    at Object.useSyncExternalStore (https://app.animeswap.org/static/js/main.e348792d.js:2:1005322)
    at t.useSyncExternalStore (https://app.animeswap.org/static/js/main.e348792d.js:2:1087846)
    at t.useSyncExternalStoreWithSelector (https://app.animeswap.org/static/js/main.e348792d.js:2:1199726)
    at https://app.animeswap.org/static/js/main.e348792d.js:2:1339828
    at Pw (https://app.animeswap.org/static/js/main.e348792d.js:2:1683025)
    at Bw (https://app.animeswap.org/static/js/main.e348792d.js:2:1683413)
    at dH (https://app.animeswap.org/static/js/main.e348792d.js:2:2052061)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "111.0.0.0",
    "major": "111"
  },
  "engine": {
    "name": "Blink",
    "version": "111.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by lobore2131** [comment]
Cant access site for 2 weeks now and i have staked aptos and ani

**Comment by Azard** [comment]
@lobore2131 try clean website localstorage and cache

**Comment by Azard** [comment]
fixed
