### ISSUE TITLE
Crash report: `Error: Invalid 'address' parameter 'ccf9ccfa82468844ec52d5b512417cbfaa41bc88'.`

### ISSUE THREAD

**Issue by babak-77** [AnimeSwap/interface#35]
## URL
  
https://staging.animeswap.org/#/swap?chain=sui_testnet

## `swap` state
    
```json
{
  "INPUT": {
    "coinId": "0x2::sui::SUI"
  },
  "OUTPUT": {
    "coinId": null
  },
  "independentField": "INPUT",
  "typedValue": ""
}
```

## Error

```
Error: Invalid 'address' parameter 'ccf9ccfa82468844ec52d5b512417cbfaa41bc88'.
```

## Stacktrace

```
Error: Invalid 'address' parameter 'ccf9ccfa82468844ec52d5b512417cbfaa41bc88'.
    at Ox (https://staging.animeswap.org/static/js/main.d387e5ba.js:2:1477878)
    at h$ (https://staging.animeswap.org/static/js/main.d387e5ba.js:117:2140)
    at _a (https://staging.animeswap.org/static/js/main.d387e5ba.js:2:877925)
    at Ts (https://staging.animeswap.org/static/js/main.d387e5ba.js:2:889613)
    at Ec (https://staging.animeswap.org/static/js/main.d387e5ba.js:2:936048)
    at vl (https://staging.animeswap.org/static/js/main.d387e5ba.js:2:924101)
    at yl (https://staging.animeswap.org/static/js/main.d387e5ba.js:2:924029)
    at ml (https://staging.animeswap.org/static/js/main.d387e5ba.js:2:923892)
    at ol (https://staging.animeswap.org/static/js/main.d387e5ba.js:2:920672)
    at cl (https://staging.animeswap.org/static/js/main.d387e5ba.js:2:921063)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "112.0.0.0",
    "major": "112"
  },
  "engine": {
    "name": "Blink",
    "version": "112.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by Azard** [comment]
What's the state of your Martian wallet @babak-77
